[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.minimal"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[settings]
generateDomain = true