[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.fixed"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10